import { CATEGORY, LEVEL } from "./enum";

const TECHNO = {
  JAVASCRIPT: {
    label: "Javascript",
    logo: "../logo/javascript.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  TYPESCRIPT: {
    label: "Typescript",
    logo: "../logo/typescript.svg",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  ANGULAR: {
    label: "Angular",
    logo: "../logo/angular.svg",
    category: CATEGORY.FRONTEND,
    level: LEVEL.INTERMEDIATE,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  REACT: {
    label: "React.JS",
    logo: "../logo/sass.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  REDUX: {
    label: "Redux",
    logo: "../logo/redux.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  HTML: {
    label: "HTML",
    logo: "../logo/html.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "5",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  CSS: {
    label: "CSS",
    logo: "../logo/css.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "3",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  ARIA_TEMPLATE: {
    label: "AriaTemplate",
    logo: "../logo/aria-template.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.BEGINNER,
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  SASS: {
    label: "Sass",
    logo: "../logo/sass.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  RAILS: {
    label: "Ruby On Rails",
    logo: "../logo/rails.svg",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  RUBY: {
    label: "Ruby",
    logo: "../logo/sass.png",
    category: CATEGORY.SCRIPTING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  SLIM: {
    label: "Slim",
    logo: "../logo/slim.png",
    category: CATEGORY.FRONTEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  GIT: {
    label: "Git",
    logo: "../logo/git.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  CLEARCASE: {
    label: "Clearcase",
    logo: "../logo/clearcase.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  JENKINS: {
    label: "Jenkins",
    logo: "../logo/jenkins.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  SWAGGER: {
    label: "Swagger",
    logo: "../logo/swagger.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  RABBIT_MQ: {
    label: "Rabbit Mq",
    logo: "../logo/rabbitmq.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  BAMBOO: {
    label: "Bamboo",
    logo: "../logo/bamboo.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  BITBUCKET: {
    label: "BitBucket",
    logo: "../logo/bitbucket.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  CONFLUENCE: {
    label: "Confluence",
    logo: "../logo/confluence.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  CODA: {
    label: "Coda",
    logo: "../logo/coda.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  DOCKER: {
    label: "Docker",
    logo: "../logo/docker.png",
    category: CATEGORY.TOOLING,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  SPRING: {
    label: "Spring",
    logo: "../logo/spring.png",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  MICRONAUT: {
    label: "Micronaut",
    logo: "../logo/micronaut.svg",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  VAADIN: {
    label: "Vaadin",
    logo: "../logo/sass.png",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  HIBERNATE: {
    label: "Hibernate",
    logo: "../logo/hibernate.png",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  JAVA: {
    label: "Java",
    logo: "../logo/java.png",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },

  // Testing
  ROBOT_FRAMEWORK: {
    label: "Robotframework",
    logo: "../logo/robotframework.png",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },

  // DEVOPS
  AWS: {
    label: "AWS Stack",
    logo: "../logo/aws.png",
    category: CATEGORY.BACKEND,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },

  MYSQL: {
    label: "MySQL",
    logo: "../logo/sass.png",
    category: CATEGORY.DATABASE,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  ORACLE: {
    label: "Oracle",
    logo: "../logo/oracle_db.webp",
    category: CATEGORY.DATABASE,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  POSTGRESQL: {
    label: "PostgreSQL",
    logo: "../logo/postgresql.png",
    category: CATEGORY.DATABASE,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
  FIREBASE: {
    label: "Firebase",
    logo: "../logo/firebase.png",
    category: CATEGORY.DATABASE,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },

  // Functional skills
  AGILE: {
    label: "Agile",
    logo: "../logo/agile.png",
    category: CATEGORY.FUNCTIONAL,
    level: LEVEL.EXPERT,
    version: "ES8",
    description: "Language used in the browser",
    purpose: "Any browser-based project, but as well any project event-based",
    links: {},
  },
};

export default TECHNO;
